export interface User {
    id: number;
    avatar: string;
    name: string;
    first_name: string;
    last_name: string;
    username: string;
    remote: boolean;
    locale: string | null;
    employee_num: string | null;
    manager: string | null;
    jobtitle: string | null;
    vip: boolean;
    phone: string | null;
    website: string | null;
    address: string | null;
    city: string | null;
    state: string | null;
    country: string | null;
    zip: string | null;
    email: string;
    department: string | null;
    location: {
        id: number;
        name: string;
    };
    notes: string | null;
    permissions: {
        superuser: string;
        admin: string;
        import: string;
        "reports.view": string;
        "assets.view": string;
        "assets.create": string;
        "assets.edit": string;
        "assets.delete": string;
        "assets.checkin": string;
        "assets.checkout": string;
        "assets.audit": string;
        "assets.view.requestable": string;
        "accessories.view": string;
        "accessories.create": string;
        "accessories.edit": string;
        "accessories.delete": string;
        "accessories.checkout": string;
        "accessories.checkin": string;
        "accessories.files": string;
        "consumables.view": string;
        "consumables.create": string;
        "consumables.edit": string;
        "consumables.delete": string;
        "consumables.checkout": string;
        "consumables.files": string;
        "licenses.view": string;
        "licenses.create": string;
        "licenses.edit": string;
        "licenses.delete": string;
        "licenses.checkout": string;
        "licenses.keys": string;
        "licenses.files": string;
        "components.view": string;
        "components.create": string;
        "components.edit": string;
        "components.delete": string;
        "components.checkout": string;
        "components.checkin": string;
        "components.files": string;
        "kits.view": string;
        "kits.create": string;
        "kits.edit": string;
        "kits.delete": string;
        "users.view": string;
        "users.create": string;
        "users.edit": string;
        "users.delete": string;
        "models.view": string;
        "models.create": string;
        "models.edit": string;
        "models.delete": string;
        "categories.view": string;
        "categories.create": string;
        "categories.edit": string;
        "categories.delete": string;
        "departments.view": string;
        "departments.create": string;
        "departments.edit": string;
        "departments.delete": string;
        "statuslabels.view": string;
        "statuslabels.create": string;
        "statuslabels.edit": string;
        "statuslabels.delete": string;
        "customfields.view": string;
        "customfields.create": string;
        "customfields.edit": string;
        "customfields.delete": string;
        "suppliers.view": string;
        "suppliers.create": string;
        "suppliers.edit": string;
        "suppliers.delete": string;
        "manufacturers.view": string;
        "manufacturers.create": string;
        "manufacturers.edit": string;
        "manufacturers.delete": string;
        "depreciations.view": string;
        "depreciations.create": string;
        "depreciations.edit": string;
        "depreciations.delete": string;
        "locations.view": string;
        "locations.create": string;
        "locations.edit": string;
        "locations.delete": string;
        "companies.view": string;
        "companies.create": string;
        "companies.edit": string;
        "companies.delete": string;
        "self.two_factor": string;
        "self.api": string;
        "self.edit_location": string;
        "self.checkout_assets": string;
        "self.view_purchase_cost": string;
    };
    activated: boolean;
    autoassign_licenses: boolean;
    ldap_import: boolean;
    two_factor_enrolled: boolean;
    two_factor_optin: boolean;
    assets_count: number;
    licenses_count: number;
    accessories_count: number;
    consumables_count: number;
    company: string | null;
    created_by: {
        id: number;
        name: string;
    };
    created_at: {
        datetime: string;
        formatted: string;
    };
    updated_at: {
        datetime: string;
        formatted: string;
    };
    start_date: string | null;
    end_date: string | null;
    last_login: {
        datetime: string;
        formatted: string;
    };
    deleted_at: string | null;
    available_actions: {
        update: boolean;
        delete: boolean;
        clone: boolean;
        restore: boolean;
    };
    groups: string | null;
    password?: string;
    secret?: string;
    locationId?: number;
}
